### ISSUE TITLE
requireNativeComponent: "RNSpinkit" was not found in the UIManager.

### ISSUE THREAD

**Issue by ithustle** [WrathChaos/react-native-dynamic-search-bar#50]
After install this library and its dependencies, my app crash with this error:

```
Invariant Violation: requireNativeComponent: "RNSpinkit" was not found in the UIManager
```
My code:

````
<SearchBar
                    height={56}
                    placeholderTextColor='#fff'
                    placeholder="Procurar oradores..."
                    spinnerVisibility={true}
                    onPress={() => alert("onPress")}
                    style={{ backgroundColor: '#14292F', borderRadius: 0, width: '100%', height: 56, shadowColor: '#14292F' }}
                    searchIconImageStyle={{ tintColor: '#fff' }}
                    clearIconImageStyle={{ tintColor: '#fff' }}
                    textInputStyle={styles.inputs}
                    onClearPress={() => null }
                    onChangeText={(text) => console.log(text)}
                />
````

**Comment by ithustle** [comment]
Installed and all good.

**Comment by WrathChaos** [comment]
@ithustle Can you prove the solution in case someone can find it :)

**Comment by ithustle** [comment]
Yep. I have to install this library https://github.com/maxs15/react-native-spinkit (following the doc) and works fine

**Comment by sayan-avantai** [comment]
The problem comes from https://www.npmjs.com/package/react-native-dynamic-search-bar. here it is mentioned that need react-native-animated-spinkit 
<img width="697" alt="Screenshot 2024-07-12 at 12 43 21 PM" src="https://github.com/user-attachments/assets/bfcd2fd5-fc33-4c2a-8141-f44c908f2009">

 But in github they have mentioned to install react-native-spinkit . Both are different libraries.
